In [1]:
import numpy as np
import pandas as pd
import cv2
import os

### translation matrix

In [5]:
img= cv2.imread(r"C:\Users\laksh\Downloads\Charmander.jpg")

In [7]:
img.shape

(225, 225, 3)

In [10]:
tx = 10
ty =10
t_m = np.array([[1,0,tx],[0,1,ty]],dtype = np.float32)

t_img = cv2.warpAffine(img,t_m,(1280,874))

In [12]:
t_m

array([[ 1.,  0., 10.],
       [ 0.,  1., 10.]], dtype=float32)

In [ ]:
cv2.imshow("or",img)
cv2.imshow("t_m",t_img)

cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
tx = 10
ty =10
t_m = np.array([[1,0,tx],[0,1,ty]],dtype = np.float32)

t_img = cv2.warpAffine(img,t_m,(1280,874), borderMode= cv2.BORDER_CONSTANT, borderValue = (0,0,255))
t_img1 = cv2.warpAffine(img,t_m,(1280,874), borderMode = cv2.BORDER_REFLECT)

In [11]:
t_m

array([[ 1.,  0., 10.],
       [ 0.,  1., 10.]], dtype=float32)

In [13]:
cv2.imshow("or",img)
cv2.imshow("t_m",t_img)
cv2.imshow("t_m1",t_img1)

cv2.waitKey()
cv2.destroyAllWindows()

### Rotation matrix

In [16]:
img.shape

(225, 225, 3)

In [18]:
25//2

12

In [20]:
r_m = cv2.getRotationMatrix2D((112,112),90,1)

In [22]:
r_m

array([[ 6.12323400e-17,  1.00000000e+00, -1.42108547e-14],
       [-1.00000000e+00,  6.12323400e-17,  2.24000000e+02]])

In [24]:
r_img = cv2.warpAffine(img, r_m, (1280,874))

In [26]:
cv2.imshow("or",img)
cv2.imshow("r_m",r_img)


cv2.waitKey()
cv2.destroyAllWindows()

### using with cv2.rotation

In [31]:
img1 = cv2.rotate(img,cv2.ROTATE_180)
img2 = cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)
img3 = cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISE)


cv2.imshow("img",img)
cv2.imshow("img1",img1)
cv2.imshow("img2",img2)
cv2.imshow("img3",img3)


cv2.waitKey()
cv2.destroyAllWindows()

### scaling -- zoom in or zoom out

In [34]:
img.shape

(225, 225, 3)

In [36]:
sx = 2
sy = 2
tx = 10
ty = 10
s_c = np.array([[sx,0,tx],[0,sy,ty]], dtype = np.float32)

In [38]:
sc_m = cv2.warpAffine(img,s_c,(2*255,2*255))


cv2.imshow("or",img)
cv2.imshow('sc_m',sc_m)

cv2.waitKey()
cv2.destroyAllWindows()

In [40]:
cv2.imshow("or",cv2.resize(img,(500,500)))
cv2.imshow('sc_m',cv2.resize(sc_m,(50,50)))

cv2.waitKey()
cv2.destroyAllWindows()

In [42]:
zo_o = cv2.pyrDown(img)
zo_i = cv2.pyrUp(img)

In [44]:
cv2.imshow("or",zo_o)
cv2.imshow('sc_m',zo_i)

cv2.waitKey()
cv2.destroyAllWindows()

### sheering

In [47]:
shx = 2
shy = 3

tx =10
ty = 10

sh_m = np.array([[1,shx,tx],[shy,1,ty]], dtype = np.float32)

In [ ]:
scal_img =cv2.warpAffine(img,sh_m,(255,255))

cv2.imshow("or",img)
cv2.imshow('sc_m',scal_img)

cv2.waitKey()
cv2.destroyAllWindows()